### ISSUE TITLE
Fatal error: ValidationException must be of type array, null given

### ISSUE THREAD

**Issue by Crag-Monkey** [anystack-sh/wp-guard#1]
I'm trying to implement Anystack into a Wordpress plugin for the first time but I get the below error after using the default "activate" form.
I get the same error when using the [Demo plugin (v 0.0.2)](https://github.com/anystack-sh/wordpress-demo-plugin/releases/tag/0.0.2) 

`Fatal error: Uncaught TypeError: Anystack\WPGuard\V001\Anystack\Sdk\Exceptions\ValidationException::setErrors(): Argument #1 ($errors) must be of type array, null given, called in \wp-content\plugins\demo-plugin\wp-guard\vendor-prefixed\anystack-sh\php-sdk\src\AnystackApi.php on line 44`

When I inspect the `$response` object, I can see that it contains a `401 Unauthorized` error.
The API Key and Product ID are both configured and valid.

**Comment by PhiloNL** [comment]
Hi @Crag-Monkey,
Can you verify if your API key has the correct permissions?

**Comment by Crag-Monkey** [comment]
It is set to a license key within the correct product that is not expired or suspended, and using a policy that has no max usage or release constraint and not requiring a fingerprint (I've also tried combinations of passing a fingerprint, not passing a fingerprint, requiring/not requiring a fingerprint). Product ID and API keys are hard-coded to rule out errors during form submission.

**Comment by Crag-Monkey** [comment]
Additional information: 
The contents of $response->json() only contains message:"Unauthenticated."
$response->psrResponse->getStatusCode(): 401
$response->psrResponse->getReasonPhrase(): Unauthorized

**Comment by Crag-Monkey** [comment]
Just realize the problem - I was passing a license key instead of an API key.

**Comment by PhiloNL** [comment]
Ah yeah, that would cause some problems. Happy the issue is resolved :)
